services:
  time-tracker:
    image: time-tracker
    build: .
    volumes:
      - config:/root/.config

  test:
    image: time-tracker-test
    build:
      context: .
      dockerfile: Dockerfile.test

volumes:
  config:
